### **Задание на повторение материала

In [1]:
import numpy as np
import pandas as pd

1. Создать одномерный массив Numpy под названием a из 12 последовательных целых чисел чисел от 12 до 24 невключительно

In [5]:
a = np.array(range(12, 24, 1))
a

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

In [6]:
type(a)

numpy.ndarray

2. Создать 5 двумерных массивов разной формы из массива a. Не использовать в аргументах метода reshape число -1.

In [10]:
a_1 = a.reshape(2, 6)
a_1

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [13]:
a_2 = a.reshape(3, 4)
a_2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [14]:
a_3 = a.reshape(4, 3)
a_3

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [15]:
a_4 = a.reshape(6, 2)
a_4

array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [16]:
a_5 = a.reshape(12, 1)
a_5

array([[12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23]])

3. Создать 5 двумерных массивов разной формы из массива a. Использовать в аргументах метода reshape число -1 (в трех примерах - для обозначения числа столбцов, в двух - для строк).

In [17]:
a_1 = a.reshape(2, -1)
a_1

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [18]:
a_2 = a.reshape(-1, 4)
a_2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [19]:
a_3 = a.reshape(4, -1)
a_3

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [21]:
a_4 = a.reshape(-1, 2)
a_4

array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [24]:
a_5 = a.reshape(12, -1)
a_5

array([[12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23]])

4. Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным?

In [25]:
a_5

array([[12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23]])

In [26]:
a_5.flatten()

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

In [27]:
type(a_5)

numpy.ndarray

In [28]:
type(a_5.flatten())

numpy.ndarray

Видимо нет, хотя логично предположить, что да.

5. Создать массив из 3 строк и 4 столбцов, состоящий из случайных чисел с плавающей запятой из нормального распределения со средним, равным 0 и среднеквадратичным отклонением, равным 1.0. Получить из этого массива одномерный массив с таким же атрибутом size, как и исходный массив.

In [37]:
m1 = np.random.normal(loc = 0, scale = 1.0, size = (3, 4))
m1

array([[ 0.01192812,  2.4713852 , -0.24295213, -0.46344623],
       [-2.274186  , -0.60621992,  0.20057222, -0.39828255],
       [-1.20859467, -0.75137319, -0.52864881, -0.53687177]])

In [38]:
m1.size

12

In [39]:
m2 = m1.reshape(1, -1)
m2

array([[ 0.01192812,  2.4713852 , -0.24295213, -0.46344623, -2.274186  ,
        -0.60621992,  0.20057222, -0.39828255, -1.20859467, -0.75137319,
        -0.52864881, -0.53687177]])

In [40]:
m2.size

12

6. Создать массив a, состоящий из целых чисел, убывающих от 20 до 0 невключительно с интервалом 2.

In [41]:
a = np.array(range(20, 0, -2))
a

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

7. Создать массив b, состоящий из 1 строки и 10 столбцов: целых чисел, убывающих от 20 до 1 невключительно с интервалом 2. В чем разница между массивами a и b?

In [43]:
b = np.array(range(20, 1, -2))[:, np.newaxis]
b

array([[20],
       [18],
       [16],
       [14],
       [12],
       [10],
       [ 8],
       [ 6],
       [ 4],
       [ 2]])

Разница в количестве строк и столбцов массивов a и b. 

8. Вертикально соединить массивы a и b. a - двумерный массив из нулей, число строк которого больше 1 и на 1 меньше, чем число строк двумерного массива b, состоящего из единиц. Итоговый массив v должен иметь атрибут size, равный 10.

In [45]:
a = np.array([[0, 0], [0, 0]])
a

array([[0, 0],
       [0, 0]])

In [46]:
b = np.array([[1, 1], [1, 1], [1, 1]])
b

array([[1, 1],
       [1, 1],
       [1, 1]])

In [50]:
c = np.vstack((a, b))
c

array([[0, 0],
       [0, 0],
       [1, 1],
       [1, 1],
       [1, 1]])

9. Создать одномерный массив а, состоящий из последовательности целых чисел от 0 до 12. Поменять форму этого массива, чтобы получилась матрица A (двумерный массив Numpy), состоящая из 4 строк и 3 столбцов. Получить матрицу At путем транспонирования матрицы A. Получить матрицу B, умножив матрицу A на матрицу At с помощью матричного умножения. Какой размер имеет матрица B? Получится ли вычислить обратную матрицу для матрицы B и почему?

In [54]:
a = np.array(range(1, 13, 1))
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [55]:
A = a.reshape(4, 3)
A

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [57]:
At = A.transpose()
At

array([[ 1,  4,  7, 10],
       [ 2,  5,  8, 11],
       [ 3,  6,  9, 12]])

In [59]:
B = np.dot(A, At)
B

array([[ 14,  32,  50,  68],
       [ 32,  77, 122, 167],
       [ 50, 122, 194, 266],
       [ 68, 167, 266, 365]])

In [60]:
B.size

16

In [61]:
B.shape

(4, 4)

In [62]:
np.linalg.inv(B)

array([[ 9.35339320e+13, -1.89435812e+12, -2.76813080e+14,
         1.85173506e+14],
       [-6.76285848e+14,  7.89000156e+14,  4.50857232e+14,
        -5.63571540e+14],
       [ 1.07196990e+15, -1.57231724e+15, -7.12752241e+13,
         5.71622562e+14],
       [-4.89217984e+14,  7.85211439e+14, -1.02768928e+14,
        -1.93224528e+14]])

Получится, так как матрица B - квадратная.

10. Инициализируйте генератор случайных числе с помощью объекта seed, равного 42.

In [64]:
np.random.seed(42)

11. Создайте одномерный массив c, составленный из последовательности 16-ти случайных равномерно распределенных целых чисел от 0 до 16 невключительно. 

In [93]:
c = np.random.randint(0, 16, 16)
c

array([ 6,  5, 13, 13,  5,  5, 12,  2,  5,  7, 10, 10,  1,  4, 13,  0])

12. Поменяйте его форму так, чтобы получилась квадратная матрица C. Получите матрицу D, поэлементно прибавив матрицу B из предыдущего вопроса к матрице C, умноженной на 10. Вычислите определитель, ранг и обратную матрицу D_inv для D.

In [94]:
C = c.reshape(4, 4)
C

array([[ 6,  5, 13, 13],
       [ 5,  5, 12,  2],
       [ 5,  7, 10, 10],
       [ 1,  4, 13,  0]])

In [97]:
D = C * 10 + B
D

array([[ 74,  82, 180, 198],
       [ 82, 127, 242, 187],
       [100, 192, 294, 366],
       [ 78, 207, 396, 365]])

In [100]:
np.linalg.det(D)

-61150400.00000001

In [104]:
np.linalg.matrix_rank(D)

4

In [106]:
D_inv = np.linalg.inv(D)
D_inv

array([[ 0.00925456,  0.01540268,  0.0027192 , -0.01563816],
       [-0.03095319,  0.01496998,  0.01613497, -0.00705768],
       [ 0.00663021,  0.0009946 , -0.01156264,  0.00748809],
       [ 0.00838326, -0.01286042,  0.00281306,  0.00196009]])

13. Приравняйте к нулю отрицательные числа в матрице D_inv, а положительные - к единице. Убедитесь, что в матрице D_inv остались только нули и единицы. С помощью функции numpy.where, используя матрицу D_inv в качестве маски, а матрицы B и C - в качестве источников данных, получите матрицу E размером 4x4.  Элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 1, должны быть равны соответствующему элементу матрицы B, а элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 0, должны быть равны соответствующему элементу матрицы C.

In [113]:
D_inv[D_inv < 0] = 0
D_inv[D_inv > 0] = 1
D_inv

array([[1., 1., 1., 0.],
       [0., 1., 1., 0.],
       [1., 1., 0., 1.],
       [1., 0., 1., 1.]])

In [120]:
B

array([[ 14,  32,  50,  68],
       [ 32,  77, 122, 167],
       [ 50, 122, 194, 266],
       [ 68, 167, 266, 365]])

In [121]:
C

array([[ 6,  5, 13, 13],
       [ 5,  5, 12,  2],
       [ 5,  7, 10, 10],
       [ 1,  4, 13,  0]])

In [125]:
? np.where

In [136]:
E = np.where(D == 1.0, B, C)
E

array([[ 6,  5, 13, 13],
       [ 5,  5, 12,  2],
       [ 5,  7, 10, 10],
       [ 1,  4, 13,  0]])